[package]
name = "kvs"
version = "0.1.0"
authors = ["Liao Yao <andersrb@gmail.com>"]
description = "A key-value store"
edition = "2018"


[dependencies]
clap = "2.32.0"
failure = "0.1.5"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
walkdir = "2"
structopt = "0.3.25"
log = "0.4.6"
env_logger = "0.6.1"
chrono = "0.4"
sled = "0.34.6"
crossbeam-skiplist = { git = "https://github.com/crossbeam-rs/crossbeam.git", branch = "master" }
num_cpus = "1.10.0"
rayon = "1.0.3"
crossbeam = "0.7.1"
tokio = { version = "1.14.0", features = ["full"] }
tokio-serde-json = "0.3.0"

[dev-dependencies]
assert_cmd = "0.11"
criterion = "0.2.11"
crossbeam-utils = "0.6.5"
predicates = "1.0.0"
rand = "0.6.5"
tempfile = "3.0.7"
walkdir = "2.2.7"
panic-control = "0.1.4"

[[bench]]
name = "engine_bench"
harness = false




